### ISSUE TITLE
Portal Live stream issue

### ISSUE THREAD

**Issue by Reda-S** [Microsoft/HoloJS#100]
Live streaming the video will destabilize the objects on the hololens (they start following the camera..). 
This only happened after the culling commit, before that it was working as expected.

**Comment by omaralcheikh** [comment]
Hello,

I am also facing this issue as well. It is kind of annoying when trying to show my app to a group of people and would be nice if we have a fix for it.

Regards,
Omar.

**Comment by Almost-Done** [comment]
Sorry for the delay. I'll take a look at this issue in the next couple of days.

**Comment by khalilkhalil25** [comment]
Hi there, are there any updates on this issue?
I've had the same problem when I'm trying to view my app on live preview.

**Comment by Almost-Done** [comment]
I pushed a  fix to the [develop/fix-mrc](https://github.com/Microsoft/HoloJS/tree/develop/fix-mrc) branch. It works for me now; please give it a try.

**Comment by omaralcheikh** [comment]
Hello Cristi,
I just tried it out and it works great.
Thank you.

**Comment by Almost-Done** [comment]
The fix is in master. Please let me know if you still experience issues with mixed reality capture.
