### ISSUE TITLE
Textures not loading MTL + OBJ Loader

### ISSUE THREAD

**Issue by omaralcheikh** [Microsoft/HoloJS#101]
[couchPoofyPillows.zip](https://github.com/Microsoft/HoloJS/files/1340866/couchPoofyPillows.zip)
Hello,

I am trying to load an object with its materials using MTL/OBJ loaders as follows:

```
 var mtlLoader = new THREE.MTLLoader();
    mtlLoader.setCrossOrigin('anonymous');
    mtlLoader.load('couchPoofyPillows.mtl', function (materials) {
        materials.preload();
        var objLoader = new THREE.OBJLoaderCustom();
        objLoader.setMaterials(materials);
            objLoader.load('couchPoofyPillows.obj', function (result) {
                scene.add(result);
            }, onProgress, onError);
    });
```

However, materials with textures on them don't show. It seems the images are not being loaded.
I tried setting material.needsUpdate on all the meshes of the object but with no luck.
Note that this works fine on edge.
Attached are the files.
Can some one please assist.

Regards,
Omar.

**Comment by Almost-Done** [comment]
There was a regressions in image loading, and a reference was missing on the image buffer; by the time the image was required for the texture, the buffer was released. The texture would read random data from memory or crash with an access violation. I created a PR with the fix and uploaded your MTL+OBJ loader working sample to [http://holojs.azurewebsites.net/v3/samples](http://holojs.azurewebsites.net/v3/samples)

**Comment by omaralcheikh** [comment]
Thank you its working great now
