### ISSUE TITLE
Provide Angle For HoloJS PreBuild as Nuget?

### ISSUE THREAD

**Issue by JimSEOW** [Microsoft/HoloJS#102]
Could we request to have Nuget version of Angle for HoloJS for Win32 and ARM
e.g. https://www.nuget.org/packages/ANGLE.WindowsStore/

**Comment by Almost-Done** [comment]
There's a HoloJs Nuget package at [https://www.nuget.org/packages/holojs/](https://www.nuget.org/packages/holojs/)

It contains everything required to use HoloJs in Win32 and UWP apps

**Comment by daniele-bordignon-kodis** [comment]
Why am I getting missing DLLs on UWP ARM apps (HoloLens 2) while building?
