### ISSUE TITLE
Promise does not resolve

### ISSUE THREAD

**Issue by omaralcheikh** [Microsoft/HoloJS#104]
Hello,

It seems that promises are not resolving when calling Promise.resolve(), an error is being thrown.
`Failure in file {PATH}}\holojs\holojshost\ScriptErrorHandling.h, line 22`

Here is a sample of what I am trying to do
```
TestPromise().then(function (text) {
    console.log('resolved');
    console.log(text);
});

function TestPromise() {
    return new Promise(function (resolve, reject) {
        console.log('entered promise');
        resolve('some text');
    });
}
```
'entered promise' is being logged and then the error is thrown.

Best Regards,
Omar.

**Comment by Almost-Done** [comment]
There was no promise continuation handler in native code. Please let me know if the fix is not complete or if you encounter more issues with promises.

**Comment by omaralcheikh** [comment]
Thank you Cristi. It works as fine.
