### ISSUE TITLE
JS cache is not cleared implying modification not effective

### ISSUE THREAD

**Issue by nosy-b** [Microsoft/HoloJS#108]
It seems that sometimes HoloJS doesn't load the new JS code but uses cached one.
Is there a way to empty its cache?
I modified some JS code and it has no effect, I can see HoloJS not having any request to the server and launch the app with some old code.

**Comment by nosy-b** [comment]
Indeed when using https://www.npmjs.com/package/http-server with force empty cache the problem still happen sometimes, HoloJS doesn't load the new JS files but use its own cache. (Edge reload correctly)

**Comment by nosy-b** [comment]
It happens at the beginning when I launch my html code with the different links _.json_ and the _.html._ When I click on the _.json_ so the _HoloWebViewer_ can start, sometimes (not often) it doesn't request the _js_ scripts described in it (holographicCamer.js, ..., myApp.js). Even if I redeploy HoloWebViewer and empty the node http-server. You think it comes from the Hololens Edge Browser?

**Comment by Almost-Done** [comment]
This is not related to the browser, but rather the way HTTP APIs used by HoloJS are caching content.

When it does not request the scripts, do you mean it does not load them at all? Or it loads an older version of them?

**Comment by nosy-b** [comment]
I loads an old version. My server doesn't show any request but the HoloWebViewer still launch the app (with some previous code)

**Comment by Almost-Done** [comment]
This should be fixed in develop/next. I added a content filter to all requests to disable all HTTP caching on the client side.
