### ISSUE TITLE
Post requests not working

### ISSUE THREAD

**Issue by omaralcheikh** [Microsoft/HoloJS#109]
Hello,

It seems that the native code does not handle post requests.
Is it possible to add it?

Regards,
Omar.

**Comment by Almost-Done** [comment]
In PR #114

**Comment by omaralcheikh** [comment]
It seems you did not handle setting the content type of the request.
kindly add the following
`m_httpContent->Headers->ContentType->MediaType = Platform::StringReference(headerPair.second.c_str());`
under `line 279` in file `XmlHttpRequest.cpp`

**Comment by omaralcheikh** [comment]
The thing is I am trying to send a json string in the request body and the server will return a 415 http status code (unsupported media type) if i dont set the media type to "application/json". 
The issue was solved when i added the mention line of code

**Comment by Almost-Done** [comment]
Got it. I used your method to set the content and it should work now. I merged the fix into master.

**Comment by omaralcheikh** [comment]
Hello Cristi,

It seems this issue has resurfaced in the latest commit. 
When i post a json string to my server, the server is receiving it as empty. I tried it on a previous commit i had and it works fine. Maybe its related to the socket io fix that you implemented.

Regards,
Omar
