### ISSUE TITLE
WebARViewer doesn't open Web samples

### ISSUE THREAD

**Issue by centigradeclemensP** [Microsoft/HoloJS#117]
I deployed the WebARViewer to the HoloLens and it displays "Please open content from a web browser"
When I open http://holojs.azurewebsites.net/samples/index.html and select one of the samples, Edge goes black but displays nothing. I tried rebooting the HL, deleted and redeployed WebARViewer multiple times, but always the same behaviour.

**Comment by centigradeclemensP** [comment]
Ah, okay, it works with  the files in v4/samples subdirectory. 
Thanks, this is a great step forward, being able to make changes to a threejs project without having to deploy to the HL.

**Comment by Almost-Done** [comment]
Yes, the script required for holographic rendering changes a little over time and we had to adjust the samples, thus the versions. It was an oversight to leave the non-versioned content there - thank you for reporting it.

**Comment by Almost-Done** [comment]
http://holojs.azurewebsites.net/samples now points to the latest version
