### ISSUE TITLE
LineBasicMaterial not working 

### ISSUE THREAD

**Issue by eliasasaid1** [Microsoft/HoloJS#122]
I was using lines geometries to draw lines  then I noticed that the "linewidth" property of linebasicmaterial  not working properly with Hololens.
Is there any solution to it?

**Comment by Almost-Done** [comment]
It turns out that lineWidth is not implemented in ANGLE. Please see this post that list some possible workarounds: [StackOverflow](https://stackoverflow.com/questions/11638883/thickness-of-lines-using-three-linebasicmaterial)

**Comment by eliasasaid1** [comment]
Thank you , tried the THREE.MeshLine workaround but it didn't work

**Comment by Almost-Done** [comment]
Sorry! There's not more that can be done in HoloJS about this.
