### ISSUE TITLE
Shadow map not working for the WebGL renderer

### ISSUE THREAD

**Issue by eliasasaid1** [Microsoft/HoloJS#125]
Hello , I've been trying to enable the shadow map along with the phong material. but once i add the below to the webgl renderer to activate the shadow map : 

_let renderer = new THREE.WebGLRenderer({ canvas: canvas, antialias: true });
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;

It gives error : 0xC0000005: Access violation reading location 0x00000000

Any idea why?

**Comment by Almost-Done** [comment]
I was not able to repro by just pasting the code above in the sample ThreeJS app. Can you please post the complete script with the repro and the stack for the access violation?

**Comment by eliasasaid1** [comment]
Thank you for your feedback,you can find below my sample code  that simulates the error : 


let isHoloJs = (typeof holographic !== 'undefined');
var terrainWidth = 512;
let canvas = document.createElement(isHoloJs ? 'exp-holo-canvas' : 'canvas');
if (!isHoloJs) {
    document.body.appendChild(canvas);
    document.body.style.margin = document.body.style.padding = 0;
    canvas.style.width = canvas.style.height = "100%";
}
var RESOURCES_LOADED = false;
var loadingManager = new THREE.LoadingManager();
var terrain;
loadingManager.onProgress = function (item, loaded, total) {
    if (RESOURCES_LOADED) {
        RESOURCES_LOADED = false;

    }
};
loadingManager.onLoad = function () {
    RESOURCES_LOADED = true;
};

var textureloader = new THREE.TextureLoader(loadingManager);
textureloader.setCrossOrigin(" ");
// object loader to load objects like antenna and dollar sign
var jsonLoader = new THREE.JSONLoader(loadingManager);

let renderer = new THREE.WebGLRenderer({ canvas: canvas, antialias: true });
//once i add shadow map to the renderer it displays the error
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;
let scene = new THREE.Scene();
let camera = (isHoloJs && holographic.renderMode > 0 ? new THREE.HolographicCamera() : new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 0.01, 1000));
let clock = new THREE.Clock();
let loader = new THREE.TextureLoader();
let material = new THREE.MeshStandardMaterial({ vertexColors: THREE.VertexColors, map: new THREE.DataTexture(new Uint8Array(3).fill(255), 1, 1, THREE.RGBFormat) });

let ambientLight = new THREE.AmbientLight(0xFFFFFF, 0.4);
let directionalLight = new THREE.DirectionalLight(0xFFFFFF, 0.5);
directionalLight.position.set(2, 2, 2);
directionalLight.castShadow = true;
let pointLight = new THREE.PointLight(0xFFFFFF, 0.5);

let cube = new THREE.Mesh(new THREE.BoxBufferGeometry(0.2, 0.2, 0.2), material.clone());

renderer.setSize(window.innerWidth, window.innerHeight);
loader.setCrossOrigin('anonymous');
material.map.needsUpdate = true;

directionalLight.position.set(0, 2, 0);

cube.position.set(0, 0, -1.5);
cube.geometry.addAttribute('color', new THREE.BufferAttribute(Float32Array.from([
    1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, // right - red
    0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, // left - blue
    0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, // top - green
    1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, // bottom - yellow
    0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, // back - cyan
    1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0 // front - purple
]), 3));
loader.load('texture.png', tex => { cube.material.map = tex; start(); }, x => x, err => start());

var collArray = [];

var terrainObject3D = new THREE.Object3D(); 
scene.add(ambientLight);
scene.add(directionalLight);
////Set up shadow properties for the light
directionalLight.shadow.mapSize.width = 2048; 
directionalLight.shadow.mapSize.height = 2048; 
directionalLight.shadow.camera.near = 0.8;
directionalLight.shadow.camera.far = 2048; 
scene.add(pointLight);
loadTerrainFromJson(terrainObject3D, "file1.json");// json of a geometry (name of files is only a sample)
collArray.push(terrain);
loadGeoFromJson(terrainObject3D, "file2.json");// json of another geometry (name of files is only a sample)
scene.add(terrainObject3D);
scene.add(cube);
scene.add(camera); // this is required for HolographicCamera to function correctly

var controls;

if (!isHoloJs || holographic.renderMode === 0) {
    camera.position.set(0, 0, 1);
    controls = new THREE.OrbitControls(camera, canvas);
}

function initColors(geometry) {
    return geometry.addAttribute('color', new THREE.BufferAttribute(new Float32Array(geometry.attributes.position.array.length).fill(1.0), 3));
}

function update(delta, elapsed) {
    window.requestAnimationFrame(() => update(clock.getDelta(), clock.getElapsedTime()));

    pointLight.position.set(0 + 2.0 * Math.cos(elapsed * 0.5), 0, -1.5 + 2.0 * Math.sin(elapsed * 0.5));

    if (camera.update) camera.update();

    renderer.render(scene, camera);
}

function start() {
    update(clock.getDelta(), clock.getElapsedTime());

    // Listen to spatial input events (hands)
    // On press, spatial mapping data is requested and the visible meshes are updated
    canvas.addEventListener("sourcepress", onSpatialSourcePress);
}

function SpatialMappingMeshes(scene) {
    var self = this;
    this.meshObjects = [];
    this.scene = scene;

    function hideMeshData() {
        for (var meshIndex in self.meshObjects) {
            self.scene.remove(self.meshObjects[meshIndex].Mesh);
        }
    }

    function showMeshData() {
        for (var meshIndex in self.meshObjects) {
            self.scene.add(self.meshObjects[meshIndex].Mesh);
        }
    }

    function idEquals(id1, id2) {
        if (id1.length !== id2.length) {
            return false;
        }

        for (var i = 0; i < id1.length; i++) {
            if (id1[i] !== id2[i]) {
                return false;
            }
        }

        return true;
    }

    this.clearMeshData = function (id) {
        if (id !== undefined) {
            for (var meshIndex in self.meshObjects) {
                if (idEquals(self.meshObjects[meshIndex].id, id)) {
                    self.scene.remove(self.meshObjects[meshIndex].mesh);
                    self.meshObjects[meshIndex].mesh.geometry.dispose();
                    self.meshObjects[meshIndex].mesh.material.dispose();
                    self.meshObjects.splice(meshIndex, 1);
                    break;
                }
            }
        }
    };

    this.setMeshData = function (surfaceData) {
        self.clearMeshData(surfaceData.id);
        //var newMeshObject = createMeshObject(surfaceData);
        var newMeshObject = createMeshObjectBuffered(surfaceData);

        self.scene.add(newMeshObject.mesh);
        self.meshObjects.push(newMeshObject);
    };

    // This method is faster to render the mesh, but does not allow easy
    // manipulation of the surface; the buffers are passed through directly to the
    // GPU
    function createMeshObjectBuffered(surface) {
        var geometry = new THREE.BufferGeometry();

        // Make copies of the incoming buffers; they get recycled after this returns
        var indices = new Uint16Array(surface.indices);
        var vertices = new Float32Array(surface.vertices);
        var normals = new Uint8Array(surface.normals);

        geometry.setIndex(new THREE.BufferAttribute(indices, 1));
        geometry.addAttribute('position', new THREE.BufferAttribute(vertices, 3));
        geometry.addAttribute('normal', new THREE.BufferAttribute(normals, 3, true));

        var vertexTransform = new THREE.Matrix4();
        vertexTransform.fromArray(surface.originToSurfaceTransform);
        geometry.applyMatrix(vertexTransform);

        return { id: surface.id, mesh: new THREE.Mesh(geometry, new THREE.MeshPhongMaterial({ color: 0xFFFFFF })) };
    }

    // This method is slower than the one above, but allows for mesh manipulation
    function createMeshObject(surface) {
        var geometry = new THREE.Geometry();

        var vertexTransform = new THREE.Matrix4();
        vertexTransform.fromArray(surface.originToSurfaceTransform);

        var normalTransform = new THREE.Matrix4();
        normalTransform.fromArray(surface.normalTransform);

        var vertexIndex = 0;
        // Iterate over vertices, normals and indices and add them to the new geometry object
        for (vertexIndex = 0; vertexIndex <= surface.vertices.length - 3; vertexIndex += 3) {
            geometry.vertices.push(new THREE.Vector3(
                surface.vertices[vertexIndex],
                surface.vertices[vertexIndex + 1],
                surface.vertices[vertexIndex + 2]
            ));
        }

        geometry.applyMatrix(vertexTransform);

        for (var indiceIndex = 0; indiceIndex <= surface.indices.length - 3; indiceIndex += 3) {
            var vertexNormals = [];
            for (var normalIndex = 0; normalIndex < 3; normalIndex++) {
                vertexNormals[normalIndex] = new THREE.Vector3(
                    surface.normals[surface.indices[indiceIndex + normalIndex]],
                    surface.normals[surface.indices[indiceIndex + normalIndex] + 1],
                    surface.normals[surface.indices[indiceIndex + normalIndex] + 2]
                );
                vertexNormals[normalIndex].applyMatrix4(normalTransform);
            }
            geometry.faces.push(
                //Data passed back from surface reconstruction uses front CW winding order
                new THREE.Face3(
                    surface.indices[indiceIndex],
                    surface.indices[indiceIndex + 1],
                    surface.indices[indiceIndex + 2],
                    vertexNormals));
        }

        return { id: surface.id, mesh: new THREE.Mesh(geometry, new THREE.MeshPhongMaterial({ color: 0xFFFFFF })) };
    }
}

var meshManager = new SpatialMappingMeshes(scene);
function onSurfaceAvailable(surfaceData) {
    meshManager.setMeshData(surfaceData);
}

function onSpatialSourcePress(spatialInputEvent) {
    window.spatialMappingOptions = { scanExtentMeters: { x: 5, y: 5, z: 3 }, trianglesPerCubicMeter: 100 };
    window.addEventListener("spatialmapping", onSurfaceAvailable);
}

window.voiceCommands = ["start", "stop"];
window.addEventListener("voicecommand", onVoiceCommand);


function onVoiceCommand(voiceEvent) {
    console.log("Voice command: " + voiceEvent.command + "; confidence: " + voiceEvent.confidence);
}

function loadTerrainFromJson(Object3DGeo, file) {
    jsonLoader.load(file, function (geometry) {
        var url2 = 'pic2.png'; // name of image is only a sample
        loader.crossOrigin = '';
        let file3 = loader.load(url2);
        file3.wrapS = file3.wrapT = THREE.RepeatWrapping;
        let terrain = new THREE.Mesh(geometry, new THREE.MeshPhongMaterial({ color: 0xffffff, map: file3 }));
        terrain.geometry.center();
        terrain.frustumCulled = false;
        terrain.geometry.verticesNeedUpdate = true;
        terrain.receiveShadow = true;
        terrain.castShadow = false;
        terrain.updateMatrix();
        Object3DGeo.add(terrain);
    });
}

function loadGeoFromJson(Object3DGeo, file) {

    jsonLoader.load(file, function (geoJson) {
        var url4 = 'pic1.png'; // name of image is only a sample
        loader.crossOrigin = '';
        let file4 = loader.load(url4);
        file4.wrapS = file4.wrapT = THREE.RepeatWrapping;
        var material = new THREE.MeshPhongMaterial({ color: 0xffffff, side: THREE.DoubleSide, map: file4 });
        var mesh = new THREE.Mesh(geoJson, material.clone());
        mesh.receiveShadow = true;
        mesh.castShadow = true;
        mesh.frustumCulled = false;
        mesh.updateMatrix();
        Object3DGeo.add(mesh);

    });
}


start();

**Comment by eliasasaid1** [comment]
Thank you for your feedback,you can find attached my sample code that simulates the error
[sample-code.txt](https://github.com/Microsoft/HoloJS/files/1570715/sample-code.txt)

**Comment by Almost-Done** [comment]
Specifying DEPTH_STENCIL as format for a Renderbuffer (used by shadowmap) is not allowed by ANGLE and it was silently ignored, causing a crash on glClear. I've switched DEPTH_STENCIL for GL_DEPTH24_STENCIL8, which is considered renderable by ANGLE (see the develop/fix-framebuffer-rendering branch.) However, shadows do not work as expected yet, I'll look into it.

**Comment by eliasasaid1** [comment]
thank you for your feedback, I'll try your branch fix while waiting your feedback regarding shadows.

**Comment by Almost-Done** [comment]
This is now fixed in the develop/fix-framebuffer-rendering branch. 

ThreeJs enabled shadows by setting a uniform value to 1 with a call to uniform1i(true). As per [WebGL spec](https://www.khronos.org/registry/webgl/specs/1.0/), this parameter should be an integer. When encountering the boolean, HoloJS ignored the call. With the fix, bool values get converted to integer and the shadow is applied by the fragment shader.

**Comment by eliasasaid1** [comment]
thank you it is working perfectly now.
