### ISSUE TITLE
Why not just build this functionality straight into Edge?

### ISSUE THREAD

**Issue by lwansbrough** [Microsoft/HoloJS#13]
Hey guys! Awesome work, you're late to the party though :) https://github.com/lwansbrough/HolographicJS

Since you guys are working for MS, is there any work being done to integrate the work done here into the Edge platform? I want to be able to do canvas.getContext('webgl-holographic') and either render straight into the shell, or request to take over the user's holographic space for rendering my own space.

I was developing HolographicJS as sort of a short term solution to this problem (though it may make some sense for some people to use this to get JS holograms on the store.)

**Comment by centigradeclemensP** [comment]
Hi lwansbrough, do you think it is possible to set up threejs with HoloJS? I think you managed in your HolographicJS. I'm pretty good at threejs but have zero experience with C++, C#, so forgive me if the answer is obvious.
I also think it would be awesome to be able to deploy 3D Objects over Edge, maybe with a similar function as "full screen" for video, to be able to tap on webgl browser content and grab it into the 3D world.

**Comment by lwansbrough** [comment]
@centigradeclemensP I'm sure it's possible. My version had an issue with it, though. I haven't tried it yet. All you have to do is download the Three.js build you want to use and load it in before your app code. How you load it in with HoloJS, I'm not sure yet. You might first try using a require/import statement, though I'm not sure if they support this yet. The other way would require you essentially concatenating your app code with the Three.js source code and running it as a single file. I don't see a way to run 2 scripts in series in the same context.

**Comment by Almost-Done** [comment]
WebVR will be the way to do this in the browser in a standardized way across devices. HoloJS makes simplifying assumptions about rendering to allow regular WebGL content to render in the HoloLens.

To run multiple scripts, simply list them in app.json. They will be executed in the order in which they appear. After adding a script to the solution, don't forget to change the "Content" property of the script file to "Yes" so it gets copied to the APPX install folder.

**Comment by adam-clarey** [comment]
Hi guys, any progress on the WebVR integration? It would be extremely useful if a user could just navigate to a url and view the scene directly from Edge the same way Vive/Rift etc can.

It would mean for less code to maintain as we would essentially need to rebuild our app plus add a lot of interactivity to get it working as a deployable UWP app.
