### ISSUE TITLE
Can't compile last master on VS2017

### ISSUE THREAD

**Issue by nosy-b** [Microsoft/HoloJS#131]
I have last Win 10 SDK (10.0.16299.91) and I can't compile the last master on VS2017
I could compile the 11th december  version (https://github.com/Microsoft/HoloJS/commit/081f2f201b47854317913dda827c56c83292b357) without any problem on VS2017.

Now I have:
```
EGLBaseCoordinateSystemProperty undeclared
EGL...
Failure #using on ..../HologramJS.winmd

```
I copied your last angle version. 

Do you have any idea?

Thanks!

**Comment by Almost-Done** [comment]
It looks like you changed the ANGLE submodule to point to holojs/webvr? That won't work without corresponding changes in HoloJS, and those changes are not ready yet.

**Comment by nosy-b** [comment]
My bad you're right!
I cloned your angle fork and I didn't check that the default branch is ms-master and not holojs/master...
It now works perfectly fine thanks Cristi!
