### ISSUE TITLE
Failure in file SpatialMapping.cpp, line 25

### ISSUE THREAD

**Issue by nosy-b** [Microsoft/HoloJS#132]
Hi!
The surface-reconstruction function works great when I deploy the ThreeJSApp-Vs2017 (and uncomment it at the end of the app.js)

But when I try to use it in my javascript application through HoloJsWebViewer-Vs2017 I got an error:
_Failure in file SpatialMapping.cpp, line 25_

Do you have any clue?

Thanks!

**Comment by Almost-Done** [comment]
The viewer app does not have the "Spatial Perception" capability enabled, which is needed to allow access to surface reconstruction. To enable it, edit the package.appxmanifest file of the viewer app:

![image](https://user-images.githubusercontent.com/22161578/34850583-4720023a-f6db-11e7-8950-b2eb07ade76d.png)

**Comment by nosy-b** [comment]
Yes I thought about that and checked for the ThreeJSApp-Vs2017 package.appx.manifest to make it similar for the WebViewer and I did (only internet and microphone are checked). There is no spatial perception activated for the ThreeJSApp but it works.
(I don't have spatial perception capabilities to enable strangely)

**Comment by Almost-Done** [comment]
I remember having to add the capability manually a couple of months ago but yesterday when I checked it was on the UI so there's some variability between versions of Visual Studio.
