### ISSUE TITLE
Socket.IO : after some time clients stop receiving messages

### ISSUE THREAD

**Issue by KatayaAyman** [Microsoft/HoloJS#133]
Hi Cristi,
 
I am implementing a holojs application with socket.io.
I noticed that the client stop receiving messages after few mins and after this error gets logged:

```
The thread 0x430 has exited with code 0 (0x0).
Failure in file c:\users\msi5\source\repos\armyapp-newlib 01-15-2017\holojs\holojshost\timers.cpp, line 106
Failure in file c:\users\msi5\source\repos\armyapp-newlib 01-15-2017\holojs\holojshost\timers.cpp, line 106
```

> Sample code:
```
var url = "#########"
var room = "abc"
var socket = io(url, {});
socket.emit("room", room);
socket.emit("message", msg)
socket.on("message", callback);
```

Thanks

**Comment by KatayaAyman** [comment]
Thank you for the reply.

I checked socket-io-chat and tried it, it worked with no issues.

So I further investigated the issue that I am having, I found that when I get those two lines on client side, the client is disconnected from the server automatically.

**Comment by Almost-Done** [comment]
There might be a correlation between those messages and socket.io not receiving messages, but those error messages do not cause the script from running. They just signal that clearTimer was called with an unknown argument. When running the socket-io-chat, you get those errors as well but the messages keep coming.

I pushed a WebSocket implementation in the develop/websocket branch. Can you checkout this branch, change the socket's transport to websocket and let me know if messages keep coming?

`var socket = io(url, { transports: ['websocket'] });`

**Comment by KatayaAyman** [comment]
I downloaded the develop/websocket branch and tried to run the ThreeJSApp project but I got some errors.

Here are the logs:

**Comment by Almost-Done** [comment]
I pushed out a fix for:
1>WebSocket.cpp(197): error C2039: 'ReceiveMode': is not a member of 'Windows::Networking::Sockets::MessageWebSocketControl'
1>WebSocket.cpp(197): error C2653: 'MessageWebSocketReceiveMode': is not a class or namespace name
1>WebSocket.cpp(197): error C2065: 'FullMessage': undeclared identifier

For the other errors, please make sure the target platform for your app is 16299 and min platform version is 14393:
![image](https://user-images.githubusercontent.com/22161578/35343956-c0fe1af6-00e0-11e8-9733-98f094d776b6.png)

**Comment by KatayaAyman** [comment]
Hi Christi,

I tried the dev branch with updates to version 10.0.16299, the application did run and I could see messages on the hololens.
But the timers messages kept coming:

![image](https://user-images.githubusercontent.com/32518396/35379592-45340aae-01bf-11e8-84c4-126776225a48.png)

**Comment by Almost-Done** [comment]
Please re-activate this bug if websockets stop receiving messages. There's not much to do about socket.io using invalid timer ids.

**Comment by KatayaAyman** [comment]
Hi Christi,

Socket still stops to receive messages even with transport websocket, and it stops receiving messages till the timers.cpp error shows in logs then it reconnects again.

Not sure that I can reactivate the issue myself.
