### ISSUE TITLE
Unicode/utf-8 characters support

### ISSUE THREAD

**Issue by eliasasaid1** [Microsoft/HoloJS#137]
Can we possibly add support for uni-coded characters (UTF-8) ?
I noticed that till now they are not supported as they are not being displayed correctly.

Thank you

**Comment by Almost-Done** [comment]
Where is UTF-8 not displayed correctly?

**Comment by eliasasaid1** [comment]
Never mind, thank you. It was an issue with three.js as i replicated the issue using three.js and the problem remained.
