### ISSUE TITLE
Socket.IO : holojs crash when socketio server is down

### ISSUE THREAD

**Issue by KatayaAyman** [Microsoft/HoloJS#150]
When we try to connect to an offline socketio server from holojs we get the below exception in "exceptions.cpp" line 553

```
Exception thrown at 0x777D2552 (KernelBase.dll) in MSIApp.exe: 0x40080201: WinRT originate error (parameters: 0x80072EFD, 0x00000037, 0x0DE6F220).
Exception thrown at 0x777D2552 in MSIApp.exe: Microsoft C++ exception: Platform::COMException ^ at memory location 0x0133EC50. HRESULT:0x80072EFD The text associated with this error code could not be found.
WinRT information: A connection with the server could not be established

```
Note that on threejs, if we tried from browser, the "connect_error" event is fired and we can handle things from there.

**Comment by Almost-Done** [comment]
Fixed in develop/next. You should get onerror and onclose events when it  can't connect or the connection is dropped; exceptions are caught and handled.
