### ISSUE TITLE
How to increase the FAR of the holographic camera frustum?

### ISSUE THREAD

**Issue by nosy-b** [Microsoft/HoloJS#155]
Hi!
It seems that the holographic camera FAR is at 10 meters.
Where can I change this value?

Thanks!

**Comment by nosy-b** [comment]
@Almost-Done any clue? Thanks!

**Comment by Almost-Done** [comment]
The far plane is hard coded for now in ANGLE.

See [HolographicSwapChain](https://github.com/Almost-Done/angle/blob/03037d30334ddbcdd77705dc99a349022cc0598b/src/libANGLE/renderer/d3d/d3d11/winrt/HolographicSwapChain11.cpp#L104)

For now, the only way to change it is to recompile ANGLE with your required value and update the ANGLE binaries in the HoloJS solution. A better solution is to make the near/far plane distances configurable from script, but that would require some design.

**Comment by nosy-b** [comment]
I changed the mFarPlaneDistance and rebuilt ANGLE, works like a charm thanks!
