### ISSUE TITLE
Cannot load a VTK model

### ISSUE THREAD

**Issue by Abeer-Alsaiari** [Microsoft/HoloJS#158]
Hi All,

I'm trying to load a vtk model into the ThreeJSApp under HoloJS. The file is small about 1.5MB. I'm using THREE.VTKLoader() assuming its supported as FBXloader etc. However, VTKLoader throws an error at:

`function parseBinary( data ){`
`--> var buffer = new Uint8Array( data ); `
`//TypeError: Typed array constructor argument is invalid`

**The header of the vtk file is**:
vtk DataFile Version 4.0
vtk output
BINARY
DATASET POLYDATA
POINTS 33950 float

The THREE.VTKLoader() works fine with threejs web based examples but couldn't fix the problem to make it works with HoloJS. Any idea?

**Comment by Abeer-Alsaiari** [comment]
I upgraded ThreeJS. Now it works with vtk ASCII files but not the BINARY vtk models as [this](https://github.com/opensim-org/three.js/blob/master/examples/models/vtk/liver.vtk).

**Comment by Almost-Done** [comment]
HoloJS does not implement TextDecoder. In the absence of TextDecoder, ThreeJS falls back to 
`decodeURIComponent(` escape( s ) ) 
to decode the string. However, the string to be decoded is not a valid URL and it throws an exception.

Chrome and Firefox implement TextDecoder so it works. Edge does not implement it so the web sample does not work in Edge. If I were to remove the TextDecoder option from ThreeJS, all browsers would throw the same exception about invalid URL.

I'll look into finding or implementing a TextDecoder class.

**Comment by Abeer-Alsaiari** [comment]
I tried the utf8 decoder courtesy of [fakedrake ](https://stackoverflow.com/users/325809/fakedrake)at [stackoverflow ](https://stackoverflow.com/questions/13356493/decode-utf-8-with-javascript)and it worked perfectly. Can you put a link to the updated branch so I can get officially updated version?
