### ISSUE TITLE
createImageData not supported

### ISSUE THREAD

**Issue by khalilkhalil25** [Microsoft/HoloJS#162]
Hi,

I am trying to call createImageData on a CanvasRenderingContext2D but I'm getting the following:

> TypeError: Object doesn't support property or method 'createImageData'

It seems it hasn't been implemented.

**Comment by Almost-Done** [comment]
That's correct, createImageData and putImageData are not implemented. Meanwhile, maybe you can make do with getImageData and drawImage?

**Comment by khalilkhalil25** [comment]
OK noted, I'll try to make due with getImageData and drawImage, Thank you.
