### ISSUE TITLE
Release mode

### ISSUE THREAD

**Issue by Reda-S** [Microsoft/HoloJS#168]
The VS solution is not building on release, it is working fine on build mode.

**Comment by Almost-Done** [comment]
What is the build error?

On May 28, 2018, at 10:52 AM, Reda-S <notifications@github.com<mailto:notifications@github.com>> wrote:


The VS solution is not building on release, it is working fine on build mode.

**Comment by Reda-S** [comment]
It is a strange compiler error:

C1001 an internal error has occurred in the compiler HoloJsHost-VS2017

I just tried the solution on a different machine and the release is building as expected... 
I guess I will close this issue, it might be something specific to that VS installation, and it would be very hard to replicate/fix if it isn't happening to you too...

Thanks.
