### ISSUE TITLE
XmlHttpRequest exception when remote HTTP server is not online

### ISSUE THREAD

**Issue by xabuloes** [Microsoft/HoloJS#173]
Hello!

So I am making some high-frequent calls to a local HTTP server with the XmlHttpRequest HoloJS implementation. This works without problems, but as soon as the remote service is not running anymore, an exception is thrown here:

```cpp
XmlHttpRequest.cpp

 if (requestMessage) {
        try {
            // The following line causes the exception to be thrown:
            responseMessage = await httpClient->SendRequestAsync(requestMessage);
        } catch (...) {
            m_status = -1;
        }
    }
```

The exception is

```
Exception thrown at 0x771A2552 (KernelBase.dll) in ThreeJSApp-Vs2017.exe: WinRT originate error - 0x80072EFD : 'A connection with the server could not be established'.
Exception thrown at 0x771A2552 in ThreeJSApp-Vs2017.exe: Microsoft C++ exception: Platform::COMException ^ at memory location 0x01AFDD30. HRESULT:0x80072EFD The text associated with this error code could not be found.
WinRT information: A connection with the server could not be established
```

I understand that there is an exception, but shouldn't it be handled by emitting the "error" event on the XmlHttpRequest handle instead of bringing the whole application to an end?

Or do I miss something here?

**Comment by Almost-Done** [comment]
You are right, the native exception should result in onerror being called. I'll get this fixed.
