### ISSUE TITLE
HTTP Requests within HoloJS?!?!

### ISSUE THREAD

**Issue by weingaunity** [Microsoft/HoloJS#175]
Hi,
i try to get x,y,z coordinates for a sphere from a remote web-service. The normal 3D mode works well within the edge-browser of the hololens. But the WebAR mode does not. The sphere is visible, but the position can not be changed. In addition, the sphere flickers.

I also do not have any idea how to debug this.

Here the Demo:
Test 2  from  http://iotdev.htlwy.ac.at/website/_wg_hololens/index.html

Here the command to modify the position of the sphere:
https://iotdev.htlwy.ac.at/thing/_wg_hololens/x?value=0
https://iotdev.htlwy.ac.at/thing/_wg_hololens/y?value=0
https://iotdev.htlwy.ac.at/thing/_wg_hololens/z?value=-5

or reset the position:
https://iotdev.htlwy.ac.at/thing/_wg_hololens/reset

Any advice?

Thx.

**Comment by Almost-Done** [comment]
So the XmlHttpRequest fails on those URLs when requested from the HoloJS app ? I'll take a look.

**Comment by weingaunity** [comment]
Hello,
thx for your reply!

With the help of the loader scripts i realized, that i have to use the XmlHTTPRequest Object. Before i used the modern fetch() command with promises.

So for me it works up to now.
I posted a further issue #176  relating the base coordinate system.

Thx.

**Comment by Almost-Done** [comment]
Please use the  develop/next branch for WebVR.
