### ISSUE TITLE
Windows 10 build 17720 breaks HoloJs Spatial Input

### ISSUE THREAD

**Issue by Reda-S** [Microsoft/HoloJS#177]
Spatial input is not working anymore on the latest Windows 10 build 17720 update.

**Comment by Almost-Done** [comment]
Thanks for letting me know.

Spatial input was not working. Also, there was an access violation when no triangles were available for a mesh. I changed the target SDK to RS4 as well.

See #179 and the develop/fix-spatial-input branch. If it fixes your issue I'll merge it into main.

**Comment by Reda-S** [comment]
It is working, thanks!
