### ISSUE TITLE
Is there a possibility to use Three GLTFLoader?

### ISSUE THREAD

**Issue by nosy-b** [Microsoft/HoloJS#180]
Hi!
I tried to use the THREE GLTFLoader but it doesn't work. (But it works fine on the computer version, Three@r87)
Any idea?

Thanks!

**Comment by Cobertos** [comment]
Post any sort of errors you're getting? Also make sure the file is properly in the manifest of your project.

**Comment by Almost-Done** [comment]
The GLTF loader works in the new version of HoloJs (develop/next branch). See the directional sound sample, which loads a GLTF model of a boom box: [http://holojs.azurewebsites.net/help/app-samples.html](http://holojs.azurewebsites.net/help/app-samples.html)
