### ISSUE TITLE
It There a way to check voice without specifying commands?

### ISSUE THREAD

**Issue by nosy-b** [Microsoft/HoloJS#182]
Hello!
I'm using with success the voice commands but I wanted to use speech recognition without having to specify commands.
Is it possible to easily modify HoloJS for that?

Thanks!

**Comment by Almost-Done** [comment]
Like an unrestricted speech recognizer?

**Comment by nosy-b** [comment]
Yes, without having to set a dictionary (limited array of words)

**Comment by Almost-Done** [comment]
That should work, with the speech recognizer in dictation mode. I'll add it to develop/next as an option to a 
 new SpeechRecognizer API.

**Comment by Almost-Done** [comment]
This is fixed in develop/next. Use it like this:
```
speechRecognizer = new SpeechRecognizer();
speechRecognizer.onresult = function (result) {
    console.log(result.text);
}
speechRecognizer.start();
```

See the https://github.com/Microsoft/HoloJS/wiki/SpeechRecognizer for more details.
