### ISSUE TITLE
Cordova integration

### ISSUE THREAD

**Issue by jdnichollsc** [Microsoft/HoloJS#19]
Hi guys,

One small question, it's support cordova apps with WebGL? Maybe a cordova plugin to support:

> "OpenGL ES calls are translated from WebGL calls by the JavaScript app"

Check an example using **Canvas/WebGL** with **[Pixi.js](http://www.pixijs.com/)** => **https://github.com/jdnichollsc/IonPhaser**

And any example with [Microsoft ACE](https://github.com/Microsoft/ace)?

What do you think? :)

**Comment by lwansbrough** [comment]
This doesn't really make sense, in my opinion. I'll try to be concise with my reasoning:

1.) 2D apps in HoloLens are basically an anti-pattern.

2.) Supporting Cordova apps would require supporting the entire Cordova platform, which would likely involve writing an insane amount of modules that don't necessarily correspond well to HoloLens functionality.

3.) I believe UWP apps currently can only choose to either render as the standard UWP 2D UI in the HoloLens shell, or they can create their own holographic context for rendering; but not both.
