### ISSUE TITLE
Console.log does not print in Output window

### ISSUE THREAD

**Issue by liuminosity** [Microsoft/HoloJS#27]
The console methods (```console.log```, ```console.error```, etc) currently only output to an array viewable in the debugger. Would be a nice for debugging if these outputs were directly viewable in the Output window in Visual Studio.

**Comment by Almost-Done** [comment]
I merged a fix for when doing native debugging; messages should now show up in the Output window (Debug).

However, I could not find a way to redirect messages when script debugging.

**Comment by BryanBo-Cao** [comment]
@liuminosity 
I put 
```
console.log("line 38 in app.js");
```
in app.js in ThreeJSApp, deployed it and run it on a HoloLens. I could see the console output from the "Output" window in Visual Studio 2015:
![console](https://user-images.githubusercontent.com/14010288/27500302-c361cecc-581c-11e7-94c9-7611fbd1c551.png)

**Comment by liuminosity** [comment]
I haven't been following this for a while, but I do believe this has been fixed. Closing--thanks for all your work
