### ISSUE TITLE
Build Failed with Fatal Errors

### ISSUE THREAD

**Issue by signaturexe** [Microsoft/HoloJS#30]
Hi,
I am getting the error(attached image) while building the solution as specified in the readme. Couldn't find a solution in the listed Issues. Can you please help in pointing out if I am missing something?

Thanks
Deepak

![holojsbuilderror](https://cloud.githubusercontent.com/assets/8899447/23337159/be0244aa-fbb2-11e6-8386-89324940ae3e.PNG)

**Comment by Almost-Done** [comment]
3 Angle projects failed to load in the solution. You are probably missing some options in your VS installation. Was there any error dialog when you opened the solution?

**Comment by Almost-Done** [comment]
This is probably caused by a missing Windows SDK. The Angle libraries target older SDKs (Windows Threshold,) while HoloJS targets newer ones (RedStone). Unfortunately this means you need to enable all of them for your installation of Visual Studio.
