### ISSUE TITLE
Cannot open include file: 'GLES2/gl2.h':No such file or directory

### ISSUE THREAD

**Issue by BryanBo-Cao** [Microsoft/HoloJS#37]
I cloned the code from this repo but still got this error
![build failed](https://user-images.githubusercontent.com/14010288/26944003-4cb8ff02-4c3c-11e7-941f-35534ab0533e.png)

**Comment by Almost-Done** [comment]
Did you clone with --recursive? You can verify this by looking for the angle directory under the directory where you cloned.

**Comment by BryanBo-Cao** [comment]
cloning with --recursive worked. Thanks!
