### ISSUE TITLE
Will this framework provide support for Windows.UI.Input.Spatial inside JS?

### ISSUE THREAD

**Issue by arcadiogarcia** [Microsoft/HoloJS#4]
Does HoloJS provide a way (or intends to provide in the future) to use SpatialGestureRecognizer from the JS files?
Or is it beyond the goal of this library and we are expected to add that functionality via C++ code?

**Comment by Almost-Done** [comment]
Yes, it will provide support for input. You should not have to write any C++ code. We're still evaluating a good mapping of HoloLens input concepts to JavaScript / DOM events.

**Comment by arcadiogarcia** [comment]
Nice, thanks!

**Comment by Almost-Done** [comment]
Sorry for the long wait time. This is now in PR and should merge to master in a couple of days.

**Comment by Almost-Done** [comment]
Basic input is now merged into master. You can set event listeners for hand pressed, released, update, lost and detected. The event  contains the location of the hand, relative to stationary frame of reference of the scene as well as the current pressed state.

Look at the WebGL or ThreeJS sample apps for examples.

If needed, please open new issues for more advanced spatial input support and we'll look into it.
