### ISSUE TITLE
Spatial mapping 

### ISSUE THREAD

**Issue by BryanBo-Cao** [Microsoft/HoloJS#41]
I've been developing an app using HoloJS and I like it. Currently I am looking for solutions to scan the environment and reconstruct a 3D model from the sensors on HoloLens and display it on a browser.
It would be great to have spatial mapping API directly from HoloJS, not just from Unity3D or DirectX.

Reference:
https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/SpatialMapping/README.md

**Comment by Almost-Done** [comment]
I'm currently working on this. I'm chasing down some issues with vertex normals and per volume transforms but I should have something to share in a couple of days.

**Comment by Almost-Done** [comment]
I've pushed  develop/spatial-mapping with initial support for this. It's rough around the edges, but the ThreeJS sample can now render scanned surface meshes. Currently it is slow-ish since it retrieves and renders too many triangles: scanned volume is fixed 20x20x5 meters at 10000 triangles fixed per cubic meter.

**Comment by Almost-Done** [comment]
Improved performance by processing surface data off the UI thread.

Added ThreeJS rendering through BufferGeometry to speed up loading.

This is merged into master now.

**Comment by SHIYUENING** [comment]
Hello, I have a question. how to config my project if i want to draw things with three.js using holoJS as well as keep the input function like those in Holotoolkit-unity? I am about to implement some 3D visualization demos with hololens. Can I build the app in Unity as a simple c# project? And if not how to add interactions and use holotoolkit sdk?

**Comment by BryanBo-Cao** [comment]
Thanks for this new feature!

Just want to give an update, when I ran the ThreeJSApp, I could see the surface with spatial mapping, also got:
```
log: THREE.Matrix4.getInverse(): can't invert matrix, determinant is 0
```
from Output in Visual Studio 2015. Hope it might help for further debugging.
