### ISSUE TITLE
External .js file described in app.json is not included in the project profile to rebuild .appxreceipe

### ISSUE THREAD

**Issue by qubick** [Microsoft/HoloJS#45]
I want to refer some external javascript libraries. I found that adding an additional file in app.json does not update .vcxproj xml files (or layoutfiles under the Debug folder after clean>rebuild solution ). Where should I explicitly specify an additional .js files to be included?

**Comment by Almost-Done** [comment]
You must add the file to the project in Visual Studio: right click on Scripts folder then choose Add.

Also make sure the Content property of the added file is set to true to have it deployed with the app:
![image](https://user-images.githubusercontent.com/22161578/27417058-4b116268-56c6-11e7-9b0c-91274b2f3982.png)

**Comment by BryanBo-Cao** [comment]
I had this issue before, when I modified my code and deployed them in HoloLens, it still ran the old version of the code.
After discussed with @qubick I realized the ```content``` property in that those files I modified was not set to be true. As such they were not deployed with the app. :(
