### ISSUE TITLE
HttpClient.GetAsync() does not return a response

### ISSUE THREAD

**Issue by odimond** [Microsoft/HoloJS#46]
Hi HoloJS,

We have an existing application that uses ThreeJS in the browser and requests JSON from a server using XmlHttpRequest (inside THREE.FileLoader) which I am trying to get running in HoloJS.

In HoloJsHost.XmlHttpRequest.DownloadAsync() the HttpClient.GetAsync() method sends the request to the server. I can see in the server's console that the request comes through and the JSON is produced, however I never get either a success or failure response message.

Thanks.

**Comment by BryanBo-Cao** [comment]
How about this issue #48 ?

**Comment by Almost-Done** [comment]
I'll take a look at this in the next couple of days. Does it sometimes work to download the JSON or is it 100% not working?

**Comment by Reda-S** [comment]
Hi Odimond,
For some reason it isn't recognizing a JSON file to be of type text (xhr->IsTextResponse() is returning false)So this is a temporary fix: just Change the following code of "XmlHttpRequest.js"
**from**
    Object.defineProperty(this, "response", {
        get: function () {
            return nativeInterface.xhr.getResponse(this.native);
        }
**to** 
    Object.defineProperty(this, "response", {
        get: function () {
            return nativeInterface.xhr.**getResponseText**(this.native);
        }

**Comment by Almost-Done** [comment]
Thank you @Reda-S for debugging this.

Indeed XMLHttpRequest.response should return text if the request type is text. I fixed the native implementation of XmlHttpRequest to not fail in getResponse if the request type is text and instead return the text.

**Comment by Almost-Done** [comment]
The fix is in master. Please re-open the issue if you encounter it again.
