### ISSUE TITLE
Help!!Can not deploy to a HoloLens!

### ISSUE THREAD

**Issue by SHIYUENING** [Microsoft/HoloJS#49]
I clone the repo and update the submodule, sample app and three app can work on Hololens emulator, but when I want to deploy it to my HoloLens through wifi, i go into Properties and select remote Machine in debugging pane, the remote ip doesn't work, it says an unsupported debugging options when i select remote Machine.. The c# project which is generated from Unity works well in my Hololens through Wifi. Does any one know the reason?

**Comment by SHIYUENING** [comment]
OK finally i can deploy it with USB but I still can not understand the reason

**Comment by Almost-Done** [comment]
Make sure only "Native" or "Script" is enabled when debugging on the HoloLens:
![image](https://user-images.githubusercontent.com/22161578/27492187-26c82ea2-57fa-11e7-8a48-6c5149bd1061.png)

**Comment by Almost-Done** [comment]
I'll close this issue for now. Please let me know if you encounter more problems.
