### ISSUE TITLE
The cube is not shown

### ISSUE THREAD

**Issue by arcadiogarcia** [Microsoft/HoloJS#5]
After building and deploying the SampleApp project successfully to the HoloLens, I tried to execute the app in debug mode. Visual Studio did not report any error or exception, but after waiting a couple of minutes for the sample to load it did not render anything. If I understand correctly, a textured spinning cube should appear somewhere around me, am I missing something? What could be the issue?

**Comment by Almost-Done** [comment]
Can you please pull the latest changes and try again? There was a debugger combination that caused JsStartDebugging to fail and prevent any further script execution. We ignore errors in JsStartDebugging now.

**Comment by arcadiogarcia** [comment]
That seems to do the trick, thanks!
