### ISSUE TITLE
setInterval causes JavascriptExceptionObject in ThreeJSApp

### ISSUE THREAD

**Issue by wassx** [Microsoft/HoloJS#52]
Hi,
I tried to run the ThreeJsApp example but when I try to use e.g.
setInterval(function() { console.log("test");}, 5);
the exception is thrown.
This seems to me a very standard functionality but can't get it working in here.

Any suggestions please?

**Comment by Almost-Done** [comment]
setInterval is not implemented. I'll get in a fix for this shortly.

**Comment by wassx** [comment]
Thank you very much!
Is there an overview where already implemented parts are listed?

**Comment by Almost-Done** [comment]
It's a little more nuanced than that. Timers are not part of the EcmaScript specification; they are a web/html standard: https://www.w3.org/TR/2011/WD-html5-20110525/timers.html

HoloJS is not designed to work with the HTML/DOM model and does not implement most things HTML. For example jquery will not work. However, a sub-set of DOM elements had to be implemented to support WebGL. We can add support for more HTML standards as needed, but there is no intent to implement all of them the way a web browser has to.

**Comment by Almost-Done** [comment]
I merged a fix for this into master. I did basic testing around set|clear interval and timeouts. Please let me know if you encounter more issues.
