### ISSUE TITLE
Is there a possibility to get camera input for processing with a qr scanner library?

### ISSUE THREAD

**Issue by wassx** [Microsoft/HoloJS#56]
Is there a possibility or plans to have parts of the view available as "camera-input", so it could be used for processing in a qr scanner?

**Comment by Almost-Done** [comment]
I threw together a prototype in the develop/camera-input branch. To get a photo from the default camera, use an Image element and set the source to be "camera://local/default". See the updated ThreeJS sample that takes a picture and uses it as a texture for the cube now.

If your scanner library does not take an Image element as input, you can draw the Image on a canvas 2d and use getImageData to get the raw pixels.

**Comment by Almost-Done** [comment]
This is now merged into master. The vanilla sample app now uses the webcam to create the texture for the cube.
