### ISSUE TITLE
ThreeJSApp - XMLHttpRequest - Access violation

### ISSUE THREAD

**Issue by DoctorDubb** [Microsoft/HoloJS#58]
The folowing code in app.js:
`   var request = new XMLHttpRequest();    
    request.open('GET', 'http://xxx', true);
    request.onload = function () {
        if (request.status >= 200 && request.status < 400) {
            // Success!
            var data = JSON.parse(request.responseText);
        } else {
            // We reached our target server, but it returned an error
        }
    };
    request.onerror = function () {
        // There was a connection error of some sort
    };
    request.send(null);
`
give me the following error:
Unhandled exception at 0x76F10AAE (ucrtbase.dll) in threejsapp.exe: 0xC0000005: Access violation reading location 0x3DC87857.

**Comment by Almost-Done** [comment]
The referenced PR should fix this. Faulty dead code.

**Comment by DoctorDubb** [comment]
This appears to be fixed in Hololens emulator - will confirm on device tomorrow - closing for now.
