### ISSUE TITLE
Threejs sample is not supporting latest version Three.js

### ISSUE THREAD

**Issue by dadvav** [Microsoft/HoloJS#66]
ThreeJs sample is using some older version and is needed to adjust sample for latest version.

In file app.js 
`this._holographicViewMatrix.elements.set(window.getViewMatrix());`
replace with 
`this._holographicViewMatrix.fromArray(window.getViewMatrix());`

**Comment by adam-clarey** [comment]
I've experienced the same. I need to use a newer version of FBXLoader which needs the newer three.js

**Comment by Almost-Done** [comment]
Thank you for the feedback! I'll rev the ThreeJS version to 87 and use your comments to fix setting the view matrix.
