### ISSUE TITLE
How to use the/where to find the HoloJsWebViewer ?

### ISSUE THREAD

**Issue by mariovde** [Microsoft/HoloJS#88]
Hi,

On https://github.com/Microsoft/HoloJS/tree/master/WebSamples, you say that "A sample viewer app is provided (HoloJsWebViewer)"
Where can this be found?
Trying to run the samples, but the web-vr protocol isn't known.

regards, Mario

**Comment by Almost-Done** [comment]
HoloJsWebViewer is an app in the solution, not a web sample. Deploy it to the device where you want to view the web-ar links then navigate to them from the browser.
