### ISSUE TITLE
Can't correctly load jpg image format

### ISSUE THREAD

**Issue by nosy-b** [Microsoft/HoloJS#95]
Loading a jpg using three : `new THREE.TextureLoader().load( "image.jpg" )` seems to mix rgba channels. (code works fine in Edge)
![bugjpg](https://user-images.githubusercontent.com/158514/30521809-e2b35e52-9bc5-11e7-8124-4892f53dd4a4.jpg)

Loading the same image in png works (colored image of the earth)

**Comment by Almost-Done** [comment]
#75

**Comment by Almost-Done** [comment]
I'll try to fix the BGR to RGB conversion to unblock you.


________________________________
